### ISSUE TITLE
Unexpected revc length error

### ISSUE THREAD

**Issue by Hphipps** [ARMmbed/mbed-os-example-aws#9]
When I try to run the AWS example program on the DISCO-L475VG-IOT01A board, this error shows up and I'm unable to figure out how to solve this issue. The AWS console reports that the device successfully connected but then the error shows up and it does not send or receive an mqtt message.

![AwsError](https://user-images.githubusercontent.com/60450555/84906598-29189200-b080-11ea-9837-7cf68a2cf75f.png)

**Comment by Hphipps** [comment]
Looks like this line is causing the error. Does anyone know how to fix this?
`auto connect_status = IotMqtt_Connect(&network_info, &connect_info, /* timeout ms */ MQTT_TIMEOUT_MS, &connection);`

**Comment by boraozgen** [comment]
See https://github.com/ARMmbed/mbed-aws-client/issues/6

**Comment by boraozgen** [comment]
This seems to be a issue with your AWS IoT policy. Test if it works with a less strict policy, such as:

```
{
   "Effect": "Allow",
   "Action": "iot:*",
   "Resource": "*"
}
```

**Comment by Hphipps** [comment]
Looks like that fixed the issue. Thanks for the help.
